Repository FFIG/ffig, pull requests merged in 2018-04, with the labels that each got.

#384 Try to fix CI errors by including space around `=` in param list.
  ffig/templates/py3.macros
Labels: bug

#388 Update clang/llvm versions in docs
  README.md
Labels: documentation

#394 N393: Initialise CGo static function pointers to NULL.
  ffig/templates/go.c.tmpl
Labels: bug

#396 N395: Fix list of output files from Python generator.
  ffig/generators/python.py
Labels: bug

#398 N397: Support building `cppmodel` objects from source strings.
  CMakeLists.txt
  ffig/FFIG.py
  tests/ffig/test_build_model.py
Labels: enhancement

#400 N399: Remove unused `TypeKind` import.
  tests/cppmodel/test_model.py
Labels: simple

#401 N261: Support for noexcept functions in Go bindings.
  ffig/templates/go.c.tmpl
Labels: enhancement

#403 N402: Add descriptions to binding generators.
  ffig/generators/__init__.py
  ffig/generators/generator_aliases.py
  ffig/generators/go.py
  ffig/generators/python.py
  tests/ffig/test_generator_list.py
Labels: enhancement
